#!/bin/bash
#
# Uses notify-send to notify the user when the execution of the command
# passed as arguments is finished.
#
# Can also be used as a finishing command on a long line of commands
# and it will notify without specifying the command.
#

notify(){
	# Store previous command's exit code
	EXIT_CODE=$?

	# If parameters are passed, execute command and store exit_code
	if [ $# -gt 0 ]; then
		"$@"
		EXIT_CODE=$?
	fi
	
	# Choose icon and message
	case $EXIT_CODE in
		# On success, could use "starred" as an icon on success
		(0) ICON=emblem-default;   MESSAGE="Finished";;
		# On fail
		(*) ICON=emblem-important; MESSAGE="Error on";;
	esac

	notify-send -i $ICON "$MESSAGE" "$*"
	tput bel
}
